### ISSUE TITLE
README を書く

### ISSUE THREAD

**Issue by satococoa** [katorie/salt#27]
もし今後誰かに見てもらう機会とか助言をもらう機会がある場合、README が書かれているかどうかでだいぶ手の出しやすさが変わってきます :memo: 

僕が素晴らしいと思ってるのは https://github.com/annict/annict の README です。
ここまでやらなくても、動かし方と使い方(ログインが必要ならログイン方法)くらい書いてあるだけでも良いと思います :smile:

**Comment by katorie** [comment]
最低限のものを #35 で書きました :bow:
